#!/bin/bash
# musiaoc

complete -W "current-directory subdirectories" disperse-music

rename-tracks () {
   echo "${BOLD}Renaming MP3 Tracks${RESET}"
   kid3-cli -c 'fromtag "%{artist} — %{album} — %{track} — %{title}" 1' *.mp3
   kid3-cli -c 'fromtag "%{artist} — %{album} — %{track} — %{title}" 2' *.mp3
   echo "${BOLD}Renaming FLAC Tracks${RESET}"
   kid3-cli -c 'fromtag "%{artist} — %{album} — %{track} — %{title}" 1' *.flac
   kid3-cli -c 'fromtag "%{artist} — %{album} — %{track} — %{title}" 2' *.flac
}

flacs-to-mp3s () {
   fd -t f -e flac -x ffmpeg -i "{}" -qscale:a 0 "{.}.mp3"
}

disperse-music () {
   case $1 in
      current-directory)
         echo "Making MP3 and FLAC directories and moving respective files in this directory"
         echo "$PWD"
         mkdir MP3
         mkdir FLAC
         echo "Moving MP3 files:"
         mv -vi *.mp3 "$PWD"/MP3
         echo "Moving FLAC files:"
         mv -vi *.flac "$PWD"/FLAC
         ;;
      subdirectories) # SOMETHING WRONG!!!
         echo "Making MP3 and FLAC directories and moving respective files in each subdirectory"
         subdirectoriesArray=(*/)
         echo "$PWD"
         echo "$subdirectoriesArray"
         for dir in "${subdirectoriesArray[@]}";
         do
            shopt -s dotglob
            shopt -s nullglob
            cd "$PWD/$dir"
            echo "$PWD"
            mkdir MP3
            mkdir FLAC
            echo "Moving MP3 files:"
            mv -vi *.mp3 "$PWD"/MP3
            echo "Moving FLAC files:"
            mv -vi *.flac "$PWD"/FLAC
         done
         ;;
   esac
}

mp3s-to-ytmp4 () {
	echo "Enter image filename:"
	read -e IMAGE_FILE
	find . -type f -name '*.mp3' -print0 | while IFS= read -r -d '' AUDIO_FILE; do
    	ffmpeg \
        	-i "${AUDIO_FILE}" \
        	-loop 1 \
        	-i "${IMAGE_FILE}" \
        	-r 15 \
        	-s 1920x1080 \
        	-c:v libx264 \
        	-tune stillimage \
        	-shortest \
        	"${AUDIO_FILE}.mp4" \
        	< /dev/null
	done
	rename -- .mp3.mp4 .mp4 *.mp3.mp4
}

ytmp4s-to-yt () {
	find . -type f -name '*.mp4' -print0 | while IFS= read -r -d '' VIDEO_FILE; do
		youtube-upload \
			--title="${VIDEO_FILE}" \
			--category="Music" \
			--privacy="unlisted" \
			--auth-browser \
			${VIDEO_FILE}
	done
}
