#!/bin/sh

# protiaon
# requires wine and protontricks

#echo "Enter Steam Library Directory:"
#read STEAM_LIBRARY_DIR
STEAM_LIBRARY_DIR="/home/miles/Games/Steam Library"

echo "Enter Steam Game Name for ID Search:"
read STEAM_GAME_NAME
protontricks -s $STEAM_GAME_NAME

echo "Enter Steam Game ID:"
read STEAM_GAME_ID

WINEPREFIX="$STEAM_LIBRARY_DIR/steamapps/compatdata/$STEAM_GAME_ID/pfx" WINEARCH="win64" winecfg
