#!/bin/sh

# protiaon

echo "Enter Steam Library Directory:"
read STEAM_LIBRARY_DIR

echo "Enter Steam Game ID (PoE is 238960, Gordian is 981430):"
read STEAM_GAME_ID

WINEPREFIX="$STEAM_LIBRARY_DIR/steamapps/compatdata/$STEAM_GAME_ID/pfx" WINEARCH="win64" winecfg
