#! /bin/sh

BSPWM_RELOAD_CONFIGURATION=$(zenity --list \
   --title="Reload Configuration File" \
   --width="240" \
   --height="240" \
   --text="Choose a configuration to reload:" \
   --column="Option" \
   "sxhkd" \
   "xrdb" \
   "tint2")

if [ $BSPWM_RELOAD_CONFIGURATION == "sxhkd" ]; then
   killall -SIGUSR1 sxhkd
elif [ $BSPWM_RELOAD_CONFIGURATION == "xrdb" ]; then
   xrdb -load .Xresources
elif [ $BSPWM_RELOAD_CONFIGURATION == "tint2" ]; then
   killall -SIGUSR1 tint2
fi
